export const ImagesPath = {
  AppLogo: require('../../Assets/Images/AppLogo.png'),
  LoginScreenCouple: require('../../Assets/Images/LoginScreenCouple.png'),
  LoginScreenHeart: require('../../Assets/Images/LoginScreenHeart.png'),
  LoginBackground: require('../../Assets/Images/LoginBackground.jpg'),
  SplashBackground: require('../../Assets/Images/SplashBackground.jpg'),
  WelcomeBackground: require('../../Assets/Images/WelcomeBackground.jpg'),
};

export const IconsPath = {
  ic_back: require('../../Assets/Icons/ic_back.png'),
  ic_cancel: require('../../Assets/Icons/ic_cancel.png'),
  ic_facebook: require('../../Assets/Icons/ic_facebook.png'),
  ic_google: require('../../Assets/Icons/ic_google.png'),
  ic_home: require('../../Assets/Icons/ic_home.png'),
  ic_people_bottom: require('../../Assets/Icons/ic_people_bottom.png'),
  ic_chat: require('../../Assets/Icons/ic_chat.png'),
  ic_swipeCard: require('../../Assets/Icons/ic_swipeCard.png'),
  ic_notification: require('../../Assets/Icons/ic_notification.png'),
  ic_menu: require('../../Assets/Icons/ic_menu.png'),
  ic_call: require('../../Assets/Icons/ic_call.png'),
  ic_videoCall: require('../../Assets/Icons/ic_videoCall.png'),
  ic_message: require('../../Assets/Icons/ic_message.png'),
  ic_contact: require('../../Assets/Icons/ic_contact.png'),
  ic_mdi_invite: require('../../Assets/Icons/ic_mdi_invite.png'),
  ic_notification_filled: require('../../Assets/Icons/ic_notification-filled.png'),
  ic_settingProfile: require('../../Assets/Icons/ic_settingProfile.png'),
  ic_user_profile: require('../../Assets/Icons/ic_user-profile.png'),
  ic_raphael_help: require('../../Assets/Icons/ic_raphael_help.png'),
  ic_heart: require('../../Assets/Icons/ic_heart.png'),
  ic_cancel_with_border: require('../../Assets/Icons/ic_cancel_with_border.png'),
  ic_heart_fill: require('../../Assets/Icons/ic_heart_fill.png'),
  ic_heart_without_fill: require('../../Assets/Icons/ic_heart_without_fill.png'),
  ic_leftArrow: require('../../Assets/Icons/ic_leftArrow.png'),
};
export default {ImagesPath, IconsPath};
